### ISSUE TITLE
Usage of PFRAC in rrtm_gas_optical_depth

### ISSUE THREAD

**Issue by m214089** [ecmwf-ifs/ecrad#11] opened 2022-09-28 10:07 UTC
Hi Robin,

PFRAC is used as intent(out) in all rrtm_taumol*.F90 routines. Following the Fortran standard that means that a compiler is free to delete all prior content on entry of this subroutine. I stumbled now upon the fact that a compiler was setting to NaN on entry in each rrtm_taumol* routine again overwriting the previous calculated values. From my understanding the intent must be inout in the rrtm_taumol* routines.  This can, depending on the compiler and/or compiler options create hard to detect errors.  

Cheerio,
Luis

**Comment by m214089** [comment] 2022-09-28 10:35
There is the same issue with the other intent(out) variables
 in the rrtm_taumol routines.

**Comment by m214089** [comment] 2022-09-28 10:41
And, one may not wonder anymore, srtm_taumol routines are affected too.

**Comment by m214089** [comment] 2022-09-28 14:04
More observations: PCOL<gases> do contain NaNs when arrays are not initialized with 0 after srtm_setcoef which means not all iterated  loops are accessing proper values?!

From my point of view a serious check of the code is required. If you need access to a machine with the NAG compiler (best to test) let me know. Checks can be done with gfortran as well I think.

**Comment by rjhogan** [comment] 2022-10-03 13:32
Hi, if a taumol routine is not setting all the values of PFRAC then the problem is not that it should be letting in values that were in the array before.  Rather we should find out why it is not setting all the values of PFRAC.  I need something reproducible on my system before I can look at this.  I remember Daniel Rieger had a problem that might have been related to him feeding in full-level and half-level temperatures/pressures, when ecRad normally only takes in half-level values of these quantities.
Please note that I didn't write the RRTMG gas optics routines :-)

**Comment by reuterbal** [comment] 2024-07-30 11:21
This has likely been rendered redundant by now, closing this issue.

**Closed by reuterbal** 2024-07-30 11:21 UTC
